// Mocks generated by Mockito 5.0.5 from annotations
// in trip_planner/test/domain/shopping/commands/item/create/shopping_item_create_command_handler_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:trip_planner/domain/shopping/repository/shopping_item_model.dart'
    as _i2;
import 'package:trip_planner/domain/shopping/repository/shopping_repository.dart'
    as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeShoppingItemModel extends _i1.Fake implements _i2.ShoppingItemModel {
}

/// A class which mocks [ShoppingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingRepository extends _i1.Mock
    implements _i3.ShoppingRepository {
  MockShoppingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> create(_i2.ShoppingItemModel? model) =>
      (super.noSuchMethod(Invocation.method(#create, [model]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> update(_i2.ShoppingItemModel? model) =>
      (super.noSuchMethod(Invocation.method(#update, [model]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  _i4.Future<_i2.ShoppingItemModel?> findById(int? id) => (super.noSuchMethod(
          Invocation.method(#findById, [id]),
          returnValue:
              Future<_i2.ShoppingItemModel?>.value(_FakeShoppingItemModel()))
      as _i4.Future<_i2.ShoppingItemModel?>);
  @override
  _i4.Future<List<_i2.ShoppingItemModel>> findAllByTripId(int? id) =>
      (super.noSuchMethod(Invocation.method(#findAllByTripId, [id]),
              returnValue: Future<List<_i2.ShoppingItemModel>>.value(
                  <_i2.ShoppingItemModel>[]))
          as _i4.Future<List<_i2.ShoppingItemModel>>);
}
